//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhishingPlatform
{
    using System;
    using System.Collections.Generic;
    
    public partial class InteractionSummary
    {
        public Nullable<int> FormID { get; set; }
        public string UserEmail { get; set; }
        public string EmailCategorySubject { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> ReceivingDate { get; set; }
        public string DataSubmission { get; set; }
    }
}
